// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DuplicatedButPastAuditCompleted { weekDuplicated: number, slotRangeActiveInWeekDuplicated: [number, number], originalWeekAuditCompleted: number, newFarmId: bigint, }