// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditCompleted } from "./AuditCompleted";
import type { AuditInherited } from "./AuditInherited";
import type { DuplicatedButPastAuditCompleted } from "./DuplicatedButPastAuditCompleted";

export type FarmStatus = { "AuditCompleted": AuditCompleted } | { "AuditInherited": AuditInherited } | { "Banned": number } | { "Duplicate": number } | { "DuplicateWithPastAuditCompleted": DuplicatedButPastAuditCompleted } | "Unassigned";