// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

export interface GCAServerResponse { Devices: Array<Device>, TimeslotOffset: bigint, signature: Array<number>, }