// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FarmStatus } from "./FarmStatus";
import type { SlotRange } from "./SlotRange";

export interface PayoutWalletAndSplit { short_id: bigint, payout_wallet: string, auditor: string, auditor_percenage_glow_weight: number, auditor_percentage_usdc_weight: number, glow_weight: number, comments: Array<string> | null, payment_tx_hash: string | null, protocol_fee_paid_week: number, status: FarmStatus | null, weeks_and_slot_ranges_to_invert_power_map: Record<number, Array<SlotRange>> | null, weeks_and_slots_to_invalidate_power_map: Record<number, Array<SlotRange>> | null, timestamp_audited_completed: bigint | null, }