// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RewardSplit } from "./RewardSplit";

export type RewardSplits = Array<RewardSplit>;
