// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotRange } from "./SlotRange";

export interface WeekAndSlotRange { week: number, slot_ranges: Array<SlotRange>, }